resource_group_name = "hubrg01"
resource_group_location = "Australia Central"
nsg_name = "hubnsg01"
virtual_network_name = "hubvnet01"
subnet_name = "hubsubnet01"
network_interface = ["vmnic0", "vmnic1"]
vm_name = ["bamboo-server", "webserver01"]
vm_size = "Standard_D2s_v3"
username = "hcloud"
storage_account_type = "Standard_LRS"
#public_ip_name = ["bamboo_public_ip", "webserver01_public_ip"]
